[build]
  command = "echo 'No build needed'"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
