[build]
  command = "echo 'No build needed'"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
